version: "3"
services:
  daemonbot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - daemonbot-code:/root/src/
      - daemonbot-bashhistory:/commandhistory
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  daemonbot-code:
  daemonbot-bashhistory:
